version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - chromadb

  chromadb:
    image: chromadb/chroma
    ports:
      - "8001:8000"






# services:
#   web:
#     build: .
#     ports:
#       - "8000:8000"
#     env_file:
#       - .env
#     depends_on:
#       - chromadb
#   chromadb:
#     image: chromadb/chroma
#     ports:
#       - "8001:8000"
